/*
 * EXTERNAL_INTERRUPT_Config.h
 *
 *  Created on: Aug 14, 2023
 *      Author: himah
 */

#ifndef MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INTERRUPT_CONFIG_H_
#define MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INTERRUPT_CONFIG_H_





#endif /* MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INTERRUPT_CONFIG_H_ */
